name: HTML Sayt CI/CD + Deploy

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodni yuklab olish
        uses: actions/checkout@v4

      - name: HTML tekshirish (ixtiyoriy)
        run: |
          echo "HTML fayllar soni: $(ls *.html | wc -l)"
          ls -la

      # Artifact (sayt fayllarini) tayyorlash
      - name: Artifact yuklash
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./   # index.html shu yerda

  deploy:
    needs: build   # build tugagandan keyin ishlaydi
    runs-on: ubuntu-latest
    permissions:
      pages: write      # Yozish ruxsati
      id-token: write   # Yangi autentifikatsiya
      
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: GitHub Pages ga deploy
        id: deployment
        uses: actions/deploy-pages@v4